### ISSUE TITLE
Update social media images

### ISSUE THREAD

**Issue by jasonwhat** [spacedogXYZ/count-every-vote#2]

**Comment by jasonwhat** [comment]
I updated these but they do not seem to be pulling for link previews or on social media. @jlev 
https://iframely.com/embed/https%3A%2F%2Fvotecounts.org

**Comment by jlev** [comment]
@jasonwhat can you drop the correct images here?

FB debugger is better to use than iframely.
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.votecounts.org

**Comment by jlev** [comment]
resolved with 2d1e0cf1fb270a8a5c329b97565e8ff291d26fd6

**Comment by jlev** [comment]
Had to add the metadata to the homepage, in cce4dee
