### ISSUE TITLE
Pages pull old open graph image and wrong description content

### ISSUE THREAD

**Issue by jasonwhat** [spacedogXYZ/count-every-vote#7]
They should get custom info from Ghost for Meta, FB and Twitter (defaulting to Meta if other two are not filled out). The title is the page title which is fine, but the description is just the first part of the page content. Mainly it’s the image that concerns me. I’d be fine with the main site share images.

**Comment by jlev** [comment]
It's giving Facebook the right URL, but it seems like the hitting their [share debugger](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.votecounts.org%2Ftexas%2F) isn't causing the image content to update. I just renamed the file in 440f508, which should fix it.

**Comment by jlev** [comment]
I hit https://developers.facebook.com/tools/debug/sharing/batch/ with 
```
https://www.votecounts.org/florida/
https://www.votecounts.org/georgia/
https://www.votecounts.org/michigan/
https://www.votecounts.org/ohio/
https://www.votecounts.org/pennsylvania/
https://www.votecounts.org/texas/
https://www.votecounts.org/wisconsin/
```
to force them to refresh their cache.
