### ISSUE TITLE
Embed Twitter Moments on Page

### ISSUE THREAD

**Issue by jasonwhat** [spacedogXYZ/count-every-vote#9]
Can you embed this on a page with the URL /live
`<a class="twitter-moment" href="https://twitter.com/i/moments/1324439854718005253?ref_src=twsrc%5Etfw">2020 Vote Count</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> `

**Comment by jlev** [comment]
added, but it is appearing with oldest tweets first. not sure if there's a way to adjust the ordering in the embed code...
